/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:fc5ebaa5-a2ca-422a-a627-43ff7c3aabd3",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_hu9ySbVPL",
    "aws_user_pools_web_client_id": "42nvidr4fn0ichdbpus87bkmip",
    "oauth": {}
};


export default awsmobile;
